package com.csu.luutailieu;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.view.*;import android.widget.*;import androidx.core.content.FileProvider;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 final int BLUE=Color.rgb(25,105,210),GREEN=Color.rgb(28,150,70),RED=Color.rgb(205,45,45); Db db; LinearLayout list; EditText search; long pickId=-1;String pickFolder="";
 public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);build();refresh();}
 TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(30,40,55));v.setPadding(10,8,10,8);if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
 Button btn(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(color);return b;}
 EditText edit(String s){EditText e=new EditText(this);e.setText(s==null?"":s);e.setTextSize(15);e.setSingleLine(false);e.setBackgroundColor(Color.WHITE);e.setPadding(12,8,12,8);return e;}
 void build(){ScrollView page=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,24,22,30);root.setBackgroundColor(Color.WHITE);page.addView(root);
  TextView title=tv("LƯU TÀI LIỆU CSU",26,true);title.setTextColor(BLUE);root.addView(title);root.addView(tv("Quản lý thiết bị và tài liệu lưu trực tiếp trên điện thoại",14,false));
  Button add=btn("+ Thêm thiết bị",BLUE);add.setOnClickListener(v->{db.add();refresh();});root.addView(add,new LinearLayout.LayoutParams(-1,-2));
  TextView sl=tv("Tìm kiếm",15,true);sl.setPadding(4,24,4,4);root.addView(sl);search=edit("");search.setHint("Nhập tên thiết bị, vị trí hoặc tài liệu...");root.addView(search,new LinearLayout.LayoutParams(-1,-2));search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){refresh();}public void afterTextChanged(android.text.Editable e){}});
  list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list,new LinearLayout.LayoutParams(-1,-2));setContentView(page);
 }
 void refresh(){if(list==null)return;list.removeAllViews();for(Db.Item d:db.list(search==null?"":search.getText().toString()))list.addView(card(d));}
 View card(Db.Item d){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(14,14,14,14);c.setBackgroundColor(Color.rgb(244,248,253));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,16,0,0);c.setLayoutParams(cp);
  c.addView(tv("Tên thiết bị",13,true));EditText n=edit(d.name);c.addView(n);c.addView(tv("Vị trí",13,true));EditText l=edit(d.location);c.addView(l);c.addView(tv("Tài liệu liên quan",13,true));EditText r=edit(d.related);r.setMinLines(2);c.addView(r);
  c.addView(tv("Thư mục",13,true));LinearLayout fs=new LinearLayout(this);fs.setOrientation(LinearLayout.HORIZONTAL);String[] names={"Hình ảnh","Video","File tài liệu"},folders={"images","videos","documents"};for(int i=0;i<3;i++){Button x=btn(names[i],BLUE);final String f=folders[i];x.setOnClickListener(v->folderDialog(d.id,f,names[Arrays.asList(folders).indexOf(f)]));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(2,2,2,2);fs.addView(x,p);}c.addView(fs);
  LinearLayout act=new LinearLayout(this);Button save=btn("Lưu",GREEN);save.setOnClickListener(v->{if(n.getText().toString().trim().isEmpty()){Toast.makeText(this,"Vui lòng nhập tên thiết bị",Toast.LENGTH_SHORT).show();return;}db.save(d.id,n.getText().toString().trim(),l.getText().toString().trim(),r.getText().toString().trim());Toast.makeText(this,"Đã lưu",Toast.LENGTH_SHORT).show();refresh();});Button del=btn("Xóa",RED);del.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Xóa thiết bị").setMessage("Xóa thiết bị và toàn bộ file của thiết bị này?").setNegativeButton("Hủy",null).setPositiveButton("Xóa",(a,b)->{deleteTree(deviceDir(d.id));db.del(d.id);refresh();}).show());act.addView(save,new LinearLayout.LayoutParams(0,-2,1));act.addView(del,new LinearLayout.LayoutParams(0,-2,1));c.addView(act);return c;}
 File base(){File x=new File(getExternalFilesDir(null),"LUU_TAI_LIEU_CSU");x.mkdirs();return x;} File deviceDir(long id){File x=new File(base(),"device_"+id);x.mkdirs();return x;} File folder(long id,String f){File x=new File(deviceDir(id),f);x.mkdirs();return x;}
 void folderDialog(long id,String f,String title){File dir=folder(id,f);File[] files=dir.listFiles();ArrayList<String> a=new ArrayList<>();a.add("+ Thêm file");if(files!=null)for(File x:files)a.add(x.getName());new AlertDialog.Builder(this).setTitle(title).setItems(a.toArray(new String[0]),(dlg,w)->{if(w==0){pickId=id;pickFolder=f;Intent in=new Intent(Intent.ACTION_OPEN_DOCUMENT);in.setType(f.equals("images")?"image/*":f.equals("videos")?"video/*":"*/*");in.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);in.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(in,88);}else openFile(files[w-1]);}).setNegativeButton("Đóng",null).show();}
 protected void onActivityResult(int rq,int rc,Intent data){super.onActivityResult(rq,rc,data);if(rq!=88||rc!=RESULT_OK||data==null)return;try{if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)copyUri(data.getClipData().getItemAt(i).getUri());}else if(data.getData()!=null)copyUri(data.getData());Toast.makeText(this,"Đã thêm file",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Không thể thêm file: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void copyUri(Uri u)throws Exception{String name="file_"+System.currentTimeMillis();android.database.Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null){int ix=c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&ix>=0)name=c.getString(ix);c.close();}File out=unique(folder(pickId,pickFolder),name);try(InputStream in=getContentResolver().openInputStream(u);OutputStream os=new FileOutputStream(out)){byte[]buf=new byte[65536];int z;while((z=in.read(buf))>0)os.write(buf,0,z);}}
 File unique(File d,String n){File f=new File(d,n);if(!f.exists())return f;int dot=n.lastIndexOf('.');String a=dot>0?n.substring(0,dot):n,b=dot>0?n.substring(dot):"";for(int i=2;;i++){f=new File(d,a+" ("+i+")"+b);if(!f.exists())return f;}}
 void openFile(File f){try{Uri u=FileProvider.getUriForFile(this,getPackageName()+".files",f);Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(u,getContentResolver().getType(u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){Toast.makeText(this,"Điện thoại chưa có ứng dụng phù hợp để mở file này",Toast.LENGTH_LONG).show();}}
 void deleteTree(File f){if(f==null||!f.exists())return;if(f.isDirectory()){File[]x=f.listFiles();if(x!=null)for(File q:x)deleteTree(q);}f.delete();}
}
